/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mk.maciekkolpaczekgridlayout;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author CP24
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        mk_jTextFieldWynik = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        mk_jButton0 = new javax.swing.JButton();
        mk_jButton1 = new javax.swing.JButton();
        mk_jButton2 = new javax.swing.JButton();
        mk_jButton3 = new javax.swing.JButton();
        mk_jButtonClear = new javax.swing.JButton();
        mk_jButtonPier = new javax.swing.JButton();
        mk_jButton4 = new javax.swing.JButton();
        mk_jButton5 = new javax.swing.JButton();
        mk_jButton6 = new javax.swing.JButton();
        mk_jButton7 = new javax.swing.JButton();
        mk_jButton8 = new javax.swing.JButton();
        mk_jButtonPot = new javax.swing.JButton();
        mk_jButton9 = new javax.swing.JButton();
        mk_jButtonWynik = new javax.swing.JButton();
        mk_jButtonDod = new javax.swing.JButton();
        mk_jButtonOde = new javax.swing.JButton();
        mk_jButtonMno = new javax.swing.JButton();
        mk_jButtonDzie = new javax.swing.JButton();
        mk_jMenuBar = new javax.swing.JMenuBar();
        mk_jMenuPlik = new javax.swing.JMenu();
        mk_jMenuItemClose = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Kalkulator");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        mk_jTextFieldWynik.setEditable(false);
        mk_jTextFieldWynik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jTextFieldWynikActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(3, 5, 2, 2));

        mk_jButton0.setText("0");
        mk_jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton0ActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButton0);

        mk_jButton1.setText("1");
        mk_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButton1);

        mk_jButton2.setText("2");
        mk_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButton2);

        mk_jButton3.setText("3");
        mk_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButton3);

        mk_jButtonClear.setText("C");
        mk_jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButtonClearActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButtonClear);

        mk_jButtonPier.setText("√");
        mk_jButtonPier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButtonPierActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButtonPier);

        mk_jButton4.setText("4");
        mk_jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButton4);

        mk_jButton5.setText("5");
        mk_jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButton5);

        mk_jButton6.setText("6");
        mk_jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButton6);

        mk_jButton7.setText("7");
        mk_jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButton7);

        mk_jButton8.setText("8");
        mk_jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButton8);

        mk_jButtonPot.setText("^");
        mk_jButtonPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButtonPotActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButtonPot);

        mk_jButton9.setText("9");
        mk_jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButton9);

        mk_jButtonWynik.setText("=");
        mk_jButtonWynik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButtonWynikActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButtonWynik);

        mk_jButtonDod.setText("+");
        mk_jButtonDod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButtonDodActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButtonDod);

        mk_jButtonOde.setText("-");
        mk_jButtonOde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButtonOdeActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButtonOde);

        mk_jButtonMno.setText("*");
        mk_jButtonMno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButtonMnoActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButtonMno);

        mk_jButtonDzie.setText("/");
        mk_jButtonDzie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButtonDzieActionPerformed(evt);
            }
        });
        jPanel2.add(mk_jButtonDzie);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mk_jTextFieldWynik)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(mk_jTextFieldWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mk_jMenuPlik.setText("Plik");

        mk_jMenuItemClose.setText("Zamknij");
        mk_jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jMenuItemCloseActionPerformed(evt);
            }
        });
        mk_jMenuPlik.add(mk_jMenuItemClose);

        mk_jMenuBar.add(mk_jMenuPlik);

        setJMenuBar(mk_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String liczba="";    int liczba1;
    int liczba2;
    String rownanie = "";
    String tekst="";
    private void mk_jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jMenuItemCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mk_jMenuItemCloseActionPerformed

    private void mk_jTextFieldWynikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jTextFieldWynikActionPerformed

    }//GEN-LAST:event_mk_jTextFieldWynikActionPerformed

    private void mk_jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton0ActionPerformed
        mk_jTextFieldWynik.setText(liczba+"0");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton0ActionPerformed

    private void mk_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton1ActionPerformed
        mk_jTextFieldWynik.setText(liczba+"1");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton1ActionPerformed

    private void mk_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton2ActionPerformed
                mk_jTextFieldWynik.setText(liczba+"2");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton2ActionPerformed

    private void mk_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton3ActionPerformed
                mk_jTextFieldWynik.setText(liczba+"3");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton3ActionPerformed

    private void mk_jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton4ActionPerformed
               mk_jTextFieldWynik.setText(liczba+"4");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton4ActionPerformed

    private void mk_jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton5ActionPerformed
                mk_jTextFieldWynik.setText(liczba+"5");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton5ActionPerformed

    private void mk_jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton6ActionPerformed
                mk_jTextFieldWynik.setText(liczba+"6");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton6ActionPerformed

    private void mk_jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton7ActionPerformed
                mk_jTextFieldWynik.setText(liczba+"7");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton7ActionPerformed

    private void mk_jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton8ActionPerformed
                mk_jTextFieldWynik.setText(liczba+"8");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton8ActionPerformed

    private void mk_jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton9ActionPerformed
               mk_jTextFieldWynik.setText(liczba+"9");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton9ActionPerformed

    private void mk_jButtonWynikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButtonWynikActionPerformed
                liczba2 = Integer.parseInt(liczba);
        if(rownanie.equals("+")){
            int wynik = liczba1 + liczba2;
            tekst = String.valueOf(wynik);
            mk_jTextFieldWynik.setText(tekst);
            liczba = "";
        }else if(rownanie.equals("-")){
            int wynik = liczba1 - liczba2;
            tekst = String.valueOf(wynik);
            mk_jTextFieldWynik.setText(tekst);
            liczba = "";
        }else if(rownanie.equals("/")){
            if(liczba2 == 0){
                mk_jTextFieldWynik.setText("Nie mozna dzielic przez 0");
                liczba = "";
            }else{
                int wynik = liczba1 / liczba2;
                tekst = String.valueOf(wynik);
                mk_jTextFieldWynik.setText(tekst);
                liczba = "";
            }
        }else if(rownanie.equals("*")){
            int wynik = liczba1 * liczba2;
            tekst = String.valueOf(wynik);
            mk_jTextFieldWynik.setText(tekst);
            liczba = "";
        }else if(rownanie.equals("^")){
            double wynik = Math.pow(liczba1,liczba2);
            tekst = String.valueOf(wynik);
            mk_jTextFieldWynik.setText(tekst);
            liczba = "";
        }
    }//GEN-LAST:event_mk_jButtonWynikActionPerformed

    private void mk_jButtonDodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButtonDodActionPerformed
        rownanie = "+";
        liczba1 = Integer.parseInt(liczba);
        liczba ="";
    }//GEN-LAST:event_mk_jButtonDodActionPerformed

    private void mk_jButtonOdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButtonOdeActionPerformed
        rownanie = "-";
        liczba1 = Integer.parseInt(liczba);
        liczba ="";
    }//GEN-LAST:event_mk_jButtonOdeActionPerformed

    private void mk_jButtonMnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButtonMnoActionPerformed
        rownanie = "*";
        liczba1 = Integer.parseInt(liczba);
        liczba ="";
    }//GEN-LAST:event_mk_jButtonMnoActionPerformed

    private void mk_jButtonDzieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButtonDzieActionPerformed
        rownanie = "/";
        liczba1 = Integer.parseInt(liczba);
        liczba ="";
    }//GEN-LAST:event_mk_jButtonDzieActionPerformed

    private void mk_jButtonPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButtonPotActionPerformed
        rownanie = "^";
        liczba1 = Integer.parseInt(liczba);
        liczba ="";
    }//GEN-LAST:event_mk_jButtonPotActionPerformed

    private void mk_jButtonPierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButtonPierActionPerformed
        liczba1 = Integer.parseInt(liczba);
        double wynik = Math.sqrt(liczba1);
        tekst = String.valueOf(wynik);
        mk_jTextFieldWynik.setText(tekst);
        liczba = "";
    }//GEN-LAST:event_mk_jButtonPierActionPerformed

    private void mk_jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButtonClearActionPerformed
        mk_jTextFieldWynik.setText("");
        liczba = "";
    }//GEN-LAST:event_mk_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mk_jButton0;
    private javax.swing.JButton mk_jButton1;
    private javax.swing.JButton mk_jButton2;
    private javax.swing.JButton mk_jButton3;
    private javax.swing.JButton mk_jButton4;
    private javax.swing.JButton mk_jButton5;
    private javax.swing.JButton mk_jButton6;
    private javax.swing.JButton mk_jButton7;
    private javax.swing.JButton mk_jButton8;
    private javax.swing.JButton mk_jButton9;
    private javax.swing.JButton mk_jButtonClear;
    private javax.swing.JButton mk_jButtonDod;
    private javax.swing.JButton mk_jButtonDzie;
    private javax.swing.JButton mk_jButtonMno;
    private javax.swing.JButton mk_jButtonOde;
    private javax.swing.JButton mk_jButtonPier;
    private javax.swing.JButton mk_jButtonPot;
    private javax.swing.JButton mk_jButtonWynik;
    private javax.swing.JMenuBar mk_jMenuBar;
    private javax.swing.JMenuItem mk_jMenuItemClose;
    private javax.swing.JMenu mk_jMenuPlik;
    private javax.swing.JTextField mk_jTextFieldWynik;
    // End of variables declaration//GEN-END:variables
}
