/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.maciejkolpaczekkalkulator;

/**
 *
 * @author CP24
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mk_jTextFieldWynik = new javax.swing.JTextField();
        mk_jButton1 = new javax.swing.JButton();
        mk_jButton0 = new javax.swing.JButton();
        mk_jButton3 = new javax.swing.JButton();
        mk_jButton2 = new javax.swing.JButton();
        mk_jButton4 = new javax.swing.JButton();
        mk_jButton5 = new javax.swing.JButton();
        mk_jButton6 = new javax.swing.JButton();
        mk_jButton7 = new javax.swing.JButton();
        mk_jButton9 = new javax.swing.JButton();
        mk_jButtonDod = new javax.swing.JButton();
        mk_jButton8 = new javax.swing.JButton();
        mk_jButtonWynik = new javax.swing.JButton();
        mk_jButtonOde = new javax.swing.JButton();
        mk_jButtonMno = new javax.swing.JButton();
        mk_jButtonPot = new javax.swing.JButton();
        mk_jButtonDzie = new javax.swing.JButton();
        mk_jButtonClear = new javax.swing.JButton();
        mk_jButtonPier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        mk_jButton1.setText("1");
        mk_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton1ActionPerformed(evt);
            }
        });

        mk_jButton0.setText("0");
        mk_jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton0ActionPerformed(evt);
            }
        });

        mk_jButton3.setText("3");
        mk_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton3ActionPerformed(evt);
            }
        });

        mk_jButton2.setText("2");
        mk_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton2ActionPerformed(evt);
            }
        });

        mk_jButton4.setText("4");
        mk_jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton4ActionPerformed(evt);
            }
        });

        mk_jButton5.setText("5");
        mk_jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton5ActionPerformed(evt);
            }
        });

        mk_jButton6.setText("6");
        mk_jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton6ActionPerformed(evt);
            }
        });

        mk_jButton7.setText("7");
        mk_jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton7ActionPerformed(evt);
            }
        });

        mk_jButton9.setText("9");
        mk_jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton9ActionPerformed(evt);
            }
        });

        mk_jButtonDod.setText("+");

        mk_jButton8.setText("8");
        mk_jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jButton8ActionPerformed(evt);
            }
        });

        mk_jButtonWynik.setText("=");

        mk_jButtonOde.setText("-");

        mk_jButtonMno.setText("*");

        mk_jButtonPot.setText("^");

        mk_jButtonDzie.setText("/");

        mk_jButtonClear.setText("C");

        mk_jButtonPier.setText("√");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mk_jTextFieldWynik)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(mk_jButton4)
                                        .addGap(13, 13, 13)
                                        .addComponent(mk_jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mk_jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mk_jButton7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(mk_jButton8)
                                        .addGap(13, 13, 13)
                                        .addComponent(mk_jButton9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mk_jButtonWynik)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mk_jButtonClear)))
                                .addGap(102, 102, 102)
                                .addComponent(mk_jButtonPot)
                                .addGap(0, 46, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(mk_jButton0)
                                .addGap(13, 13, 13)
                                .addComponent(mk_jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mk_jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mk_jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mk_jButtonOde, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mk_jButtonPier)
                                    .addComponent(mk_jButtonMno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mk_jButtonDzie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mk_jButtonDod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(mk_jTextFieldWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mk_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mk_jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mk_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mk_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mk_jButtonDod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mk_jButtonOde, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mk_jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mk_jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mk_jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mk_jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mk_jButtonDzie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mk_jButtonMno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mk_jButtonPot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mk_jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mk_jButtonWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mk_jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mk_jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mk_jButtonPier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String liczba="";
    private void mk_jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton0ActionPerformed
        mk_jTextFieldWynik.setText(liczba+"0");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton0ActionPerformed

    private void mk_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton1ActionPerformed
        mk_jTextFieldWynik.setText(liczba+"1");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton1ActionPerformed

    private void mk_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton2ActionPerformed
        mk_jTextFieldWynik.setText(liczba+"2");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton2ActionPerformed

    private void mk_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton3ActionPerformed
        mk_jTextFieldWynik.setText(liczba+"3");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton3ActionPerformed

    private void mk_jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton4ActionPerformed
        mk_jTextFieldWynik.setText(liczba+"4");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton4ActionPerformed

    private void mk_jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton5ActionPerformed
        mk_jTextFieldWynik.setText(liczba+"5");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton5ActionPerformed

    private void mk_jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton6ActionPerformed
        mk_jTextFieldWynik.setText(liczba+"6");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton6ActionPerformed

    private void mk_jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton7ActionPerformed
        mk_jTextFieldWynik.setText(liczba+"7");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton7ActionPerformed

    private void mk_jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton8ActionPerformed
        mk_jTextFieldWynik.setText(liczba+"8");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton8ActionPerformed

    private void mk_jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jButton9ActionPerformed
        mk_jTextFieldWynik.setText(liczba+"9");
        liczba=mk_jTextFieldWynik.getText();
    }//GEN-LAST:event_mk_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mk_jButton0;
    private javax.swing.JButton mk_jButton1;
    private javax.swing.JButton mk_jButton2;
    private javax.swing.JButton mk_jButton3;
    private javax.swing.JButton mk_jButton4;
    private javax.swing.JButton mk_jButton5;
    private javax.swing.JButton mk_jButton6;
    private javax.swing.JButton mk_jButton7;
    private javax.swing.JButton mk_jButton8;
    private javax.swing.JButton mk_jButton9;
    private javax.swing.JButton mk_jButtonClear;
    private javax.swing.JButton mk_jButtonDod;
    private javax.swing.JButton mk_jButtonDzie;
    private javax.swing.JButton mk_jButtonMno;
    private javax.swing.JButton mk_jButtonOde;
    private javax.swing.JButton mk_jButtonPier;
    private javax.swing.JButton mk_jButtonPot;
    private javax.swing.JButton mk_jButtonWynik;
    private javax.swing.JTextField mk_jTextFieldWynik;
    // End of variables declaration//GEN-END:variables
}
