/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.maciejkolpaczekprzeliczenia;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author CP24
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mk_jPanelGlowny = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        mk_jMenuBar = new javax.swing.JMenuBar();
        mk_jMenuPlik = new javax.swing.JMenu();
        mk_jMenuItemHistoria = new javax.swing.JMenuItem();
        mk_jMenuItemZamknij = new javax.swing.JMenuItem();
        mk_jMenuProgram = new javax.swing.JMenu();
        mk_jMenuItemProgram = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Przeliczanie Jednostek");
        setResizable(false);

        mk_jPanelGlowny.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Podaj co chcesz przeliczyc");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Odleglosc", "Temperatura" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Podaj wartosc: (jednostka)");

        jLabel3.setText("Nowa wartosc (jednostka)");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setText("Historia obliczen");

        javax.swing.GroupLayout mk_jPanelGlownyLayout = new javax.swing.GroupLayout(mk_jPanelGlowny);
        mk_jPanelGlowny.setLayout(mk_jPanelGlownyLayout);
        mk_jPanelGlownyLayout.setHorizontalGroup(
            mk_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mk_jPanelGlownyLayout.createSequentialGroup()
                .addGroup(mk_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mk_jPanelGlownyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mk_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mk_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(mk_jPanelGlownyLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mk_jPanelGlownyLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField1))
                                .addGroup(mk_jPanelGlownyLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField2)))))
                    .addGroup(mk_jPanelGlownyLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel4)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        mk_jPanelGlownyLayout.setVerticalGroup(
            mk_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mk_jPanelGlownyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mk_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mk_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mk_jPanelGlownyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mk_jMenuPlik.setText("Plik");

        mk_jMenuItemHistoria.setText("Pokaz historie");
        mk_jMenuItemHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jMenuItemHistoriaActionPerformed(evt);
            }
        });
        mk_jMenuPlik.add(mk_jMenuItemHistoria);

        mk_jMenuItemZamknij.setText("Zamknij ");
        mk_jMenuItemZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jMenuItemZamknijActionPerformed(evt);
            }
        });
        mk_jMenuPlik.add(mk_jMenuItemZamknij);

        mk_jMenuBar.add(mk_jMenuPlik);

        mk_jMenuProgram.setText("O programie");

        mk_jMenuItemProgram.setText("O programie");
        mk_jMenuItemProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk_jMenuItemProgramActionPerformed(evt);
            }
        });
        mk_jMenuProgram.add(mk_jMenuItemProgram);

        mk_jMenuBar.add(mk_jMenuProgram);

        setJMenuBar(mk_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mk_jPanelGlowny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mk_jPanelGlowny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mk_jMenuItemZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jMenuItemZamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mk_jMenuItemZamknijActionPerformed

    private void mk_jMenuItemProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jMenuItemProgramActionPerformed
        JOptionPane.showMessageDialog(null, "Witaj w programie, który jest w stanie przeliczyc metry na kilometry oraz kelwiny na celsjusze. Program  zostal wykonany przez Macieja Kolpaczka");
    }//GEN-LAST:event_mk_jMenuItemProgramActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String jednostka = (String) jComboBox1.getSelectedItem();
        if(jednostka.equals("Temperatura")){
            jLabel2.setText("Wprowadź wartość którą chcesz przeliczyć (kelwiny): ");
        }else{
            jLabel2.setText("Wprowadź wartość którą chcesz przeliczyć (metry): ");
        }
        if(jednostka.equals("Temperatura")){
            jLabel3.setText("Przeliczona wartość (stopnie Celsjusza): ");
        }else{
            jLabel3.setText("Przeliczona wartość (kilometry): ");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        String dane =("");
        String jednostka = (String) jComboBox1.getSelectedItem();
        if(jednostka.equals("Temperatura")){
            String wpisane = jTextField1.getText();
            int kelwiny = Integer.parseInt(wpisane);
            double celsjusze = kelwiny-273;
            String tekst =String.valueOf(celsjusze);
            jTextField2.setText(tekst);
            dane = "t;k= "+kelwiny+";c= "+celsjusze;
        }else{
            String wpisane = jTextField1.getText();
            double metry = Integer.parseInt(wpisane);
            double kilometry = metry/1000;
            String tekst =String.valueOf(kilometry);

            jTextField2.setText(tekst);
            dane = "o;m= "+metry+";km= "+kilometry+"\n";
        }
        File f = new File("HistoriaObliczen.txt");
        try{
            FileWriter fw = new FileWriter(f,true);
            fw.write(dane+"\n");
            fw.close();
        } catch(IOException e){
            System.out.println("błąd: "+e.toString());
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void mk_jMenuItemHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk_jMenuItemHistoriaActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showDialog(this,"Wybierz plik");
        try {
            String text ="";
            File f = jFileChooser.getSelectedFile();
            Scanner sc = new Scanner(f);
            while(sc.hasNext()){
                text = text+sc.nextLine()+"\n";
            }
            jTextArea1.setText(text);
        }catch (FileNotFoundException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_mk_jMenuItemHistoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenuBar mk_jMenuBar;
    private javax.swing.JMenuItem mk_jMenuItemHistoria;
    private javax.swing.JMenuItem mk_jMenuItemProgram;
    private javax.swing.JMenuItem mk_jMenuItemZamknij;
    private javax.swing.JMenu mk_jMenuPlik;
    private javax.swing.JMenu mk_jMenuProgram;
    private javax.swing.JPanel mk_jPanelGlowny;
    // End of variables declaration//GEN-END:variables
}
